apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jrichter/chbot:ec6442eb87427f3a47b996f456c1f021a045d3ba@sha256:fa4e2b8808259bfc3cd93f109799cf504e819e837bb7cd763d283933367ad11c # use pre-built to bootstrap
          name: app-inference
